-- Add kelas table to smkn1_kurikulum_v3 database
USE smkn1_kurikulum_v3;

CREATE TABLE kelas (
  id_kelas INT AUTO_INCREMENT PRIMARY KEY,
  nama_kelas VARCHAR(20) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert all kelas data
INSERT INTO kelas (nama_kelas) VALUES 
('X TL'),
('X TJKT 1'),
('X TJKT 2'),
('X AKL 1'),
('X AKL 2'),
('X AKL 3'),
('X TO 1'),
('X TO 2'),
('X TO 3'),
('X MPLB 1'),
('X MPLB 2'),
('X MPLB 3'),
('X TM 1'),
('X TM 2'),
('X TM 3'),
('X KL'),
('X PS 1'),
('X PS 2'),
('X DKV 1'),
('X DKV 2'),
('X PPLG 1'),
('X PPLG 2'),
('X PS 3'),
('X PS 4'),
('XI KL'),
('XI DKV 1'),
('XI DKV 2'),
('XI TPM 1'),
('XI TDM 2'),
('XI TSM 1'),
('XI RPL 2'),
('XI MP 1'),
('XI TL'),
('XI TKJ 2'),
('XII TKJ 1'),
('XII AK 1'),
('XII DKV 1'),
('XII KL'),
('XII TKJ 2'),
('XII AK 2'),
('XII DKV 2'),
('XII RPL 1'),
('XII TPM 1'),
('XII TSM 1'),
('XII MP 1'),
('XII BR 1'),
('XII TPM 2'),
('XII TSM 2'),
('XII MP 2'),
('XII BR 2'),
('XII TPM 3'),
('XII TSM 3'),
('XII MP 3'),
('XII BR 3'),
('XII TL'),
('XII AK 3'),
('XII RPL 2'),
('XII BD');